# Generated by Django 3.1.8 on 2022-02-04 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Fale brevemente sobre o produto e suas caracteristicas mais importantes', max_length=1000, verbose_name='Descrição')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Descrição Curta')),
                ('product_information', models.TextField(blank=True, help_text='Descreva como esta o estado do produto', max_length=1000, verbose_name='Informação do Produto')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Quantidade em estoque')),
                ('available', models.BooleanField(default=True, verbose_name='Disponível')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='OpenSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislike_list', models.ManyToManyField(blank=True, related_name='unlikes', to='model.Products', verbose_name='Lista de Não Curtidos')),
                ('like_list', models.ManyToManyField(blank=True, related_name='likes', to='model.Products', verbose_name='Lista de Curtidos')),
                ('match', models.ManyToManyField(blank=True, related_name='matches', to='model.Products', verbose_name='Lista de Combinações')),
                ('own_product', models.OneToOneField(blank=True, help_text='Esse é o Produto que esta em busca, estar em qualquer uma das listas resultará em erro', on_delete=django.db.models.deletion.CASCADE, to='model.products', verbose_name='Produto em Busca')),
            ],
            options={
                'verbose_name': 'Aberto para Busca',
                'verbose_name_plural': 'Abertos para Busca',
            },
        ),
    ]
